var AttendsConstants = {
  ATTENDS_RECEIVED: "ATTENDS_RECEIVED",
  SINGLE_ATTEND_RECEIVED: "SINGLE_ATTEND_RECEIVED",
  ATTENDS_RECEIVED_FOR_USER: "ATTENDS_RECEIVED_FOR_USER"
};

module.exports = AttendsConstants;
